import type { Config } from 'tailwindcss';

export default {
  darkMode: ['selector', '[data-mode="dark"]'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        'secondary-bg': 'hsl(var(--secondary-bg))',
        'tertiary-bg': 'hsl(var(--tertiary-bg))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
          // bg: 'hsl(var(--secondary-bg))',
        },
        // tertiary: {
        //   DEFAULT: 'hsl(var(--tertiary-bg))',
        //   bg: 'hsl(var(--tertiary-bg))',
        // },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
  safelist: [
    'text-neutral-400',
    'text-blue-400',
    'text-indigo-500',
    'text-violet-600',
    'text-fuchsia-600',
    'text-red-500',
    'text-yellow-600',
    'bg-neutral-400',
    'bg-blue-400',
    'bg-indigo-500',
    'bg-violet-600',
    'bg-fuchsia-600',
    'bg-red-500',
    'bg-yellow-600',
    'border-neutral-400',
    'border-blue-400',
    'border-indigo-500',
    'border-violet-600',
    'border-fuchsia-600',
    'border-red-500',
    'border-yellow-600',
    'bg-gradient-to-b',
    'bg-background',
    'from-transparent',
    'to-neutral-400',
    'to-blue-400',
    'to-indigo-500',
    'to-violet-600',
    'to-fuchsia-600',
    'to-red-500',
    'to-yellow-600',
  ],
} satisfies Config;
